### ISSUE TITLE
People complain that the script stops opening some time after the server is running. No console errors on client or server

### ISSUE THREAD

**Issue by nevypt** [blockba5her/FiveM-Emotes#4] opened 2018-03-01 02:15 UTC

**Comment by DevBlocky** [comment] 2019-04-07 00:07
I'm about to push an update that will hopefully fix this, but I really don't know what the cause of your issue would be as it's a very simple script that shouldn't do something like that. Maybe a problem with FiveM? Try updating your server or something like that, for now I'm closing this issue.

**Closed as completed by DevBlocky** 2019-04-07 00:07 UTC
